/**
 * generate-sdk.ts
 * Generates TypeScript SDK types from the OpenAPI spec using openapi-typescript.
 * Output goes to packages/sdk-generated/ as a lightweight type-only package.
 *
 * Usage: npx tsx scripts/generate-sdk.ts
 * Requires: generate:openapi to have been run first (reads docs/openapi.json).
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const docsDir = join(root, 'docs');
const sdkDir = join(root, 'packages', 'sdk-generated');

async function main() {
  const specPath = join(docsDir, 'openapi.json');

  try {
    await readFile(specPath, 'utf-8');
  } catch {
    console.error(`docs/openapi.json not found. Run 'npm run generate:openapi' first.`);
    process.exit(1);
  }

  await mkdir(sdkDir, { recursive: true });

  const typesPath = join(sdkDir, 'types.d.ts');
  const openapiTsBin = join(root, 'node_modules', '.bin', 'openapi-typescript');

  console.log('Generating TypeScript types from OpenAPI spec...');
  try {
    const { stdout } = await execFileAsync(openapiTsBin, [specPath, '--output', typesPath]);
    if (stdout) console.log(stdout);
  } catch (err: unknown) {
    const execErr = err as { stderr?: string; message?: string };
    console.error('openapi-typescript failed:', execErr.stderr ?? execErr.message);
    process.exit(1);
  }

  // Write a minimal package.json for the generated SDK
  const pkgJson = {
    name: '@screenforge/sdk-generated',
    version: '0.0.0',
    description: 'Auto-generated TypeScript types for ScreenForge API (do not edit)',
    types: 'types.d.ts',
    private: true,
    note: 'Generated by npm run generate:sdk — do not edit manually',
  };
  await writeFile(join(sdkDir, 'package.json'), JSON.stringify(pkgJson, null, 2) + '\n', 'utf-8');

  // Write a README
  await writeFile(
    join(sdkDir, 'README.md'),
    `# @screenforge/sdk-generated\n\n` +
    `Auto-generated TypeScript types from the ScreenForge OpenAPI spec.\n\n` +
    `**Do not edit manually.** Regenerate with:\n\n` +
    '```sh\nnpm run generate:openapi\nnpm run generate:sdk\n```\n',
    'utf-8',
  );

  console.log(`Wrote ${typesPath}`);
  console.log(`Wrote ${join(sdkDir, 'package.json')}`);
  console.log('SDK types generation complete.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
