/** Curated blocklist of common advertising domains. */
export const AD_DOMAINS: readonly string[] = [
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'google-analytics.com',
  'googletagmanager.com',
  'googletagservices.com',
  'pagead2.googlesyndication.com',
  'adservice.google.com',
  'amazon-adsystem.com',
  'facebook.com/tr',
  'fbcdn.net',
  'connect.facebook.net',
  'adnxs.com',
  'adsrvr.org',
  'rubiconproject.com',
  'pubmatic.com',
  'openx.net',
  'casalemedia.com',
  'indexww.com',
  'criteo.com',
  'criteo.net',
  'outbrain.com',
  'taboola.com',
  'moatads.com',
  'doubleverify.com',
  'adsafeprotected.com',
  'quantserve.com',
  'scorecardresearch.com',
  'bluekai.com',
  'exelator.com',
  'eyeota.net',
  'advertising.com',
  'adobedtm.com',
  'demdex.net',
  'everesttech.net',
  'contextweb.com',
  'media.net',
  'yieldmanager.com',
  'serving-sys.com',
  'sizmek.com',
  'bidswitch.net',
  'sharethrough.com',
  'spotxchange.com',
  'mathtag.com',
  'lijit.com',
  'sovrn.com',
  'ad.atdmt.com',
  'turn.com',
  'adform.net',
  'smartadserver.com',
] as const;

/** Check whether a hostname belongs to a known ad domain. */
export function isAdDomain(hostname: string): boolean {
  const lower = hostname.toLowerCase();
  return AD_DOMAINS.some(
    (domain) => lower === domain || lower.endsWith(`.${domain}`),
  );
}
